"""create forest model

Revision ID: aa838f139453
Revises: 
Create Date: 2022-03-29 11:14:53.255300

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa838f139453"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forest",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM("Conservation", "Reforestation", name="type"),
            nullable=True,
        ),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("country", sa.VARCHAR(), nullable=True),
        sa.Column("country_code", sa.VARCHAR(), nullable=True),
        sa.Column("image_url", sa.VARCHAR(), nullable=True),
        sa.Column("carbon_stored", sa.FLOAT(), nullable=True),
        sa.Column("carbon_stored_30_days", sa.FLOAT(), nullable=True),
        sa.Column(
            "bear_mortality",
            postgresql.ENUM("Low", "Medium", "High", "N/A", name="bear_mortality"),
            nullable=True,
        ),
        sa.Column(
            "critical_fire_risk",
            postgresql.ENUM("Low", "Medium", "High", "N/A", name="critical_fire_risk"),
            nullable=True,
        ),
        sa.Column(
            "stream_flow",
            postgresql.ENUM("Low", "Medium", "High", "N/A", name="stream_flow"),
            nullable=True,
        ),
        sa.Column("area_sqm", sa.FLOAT(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forest")
    # ### end Alembic commands ###
